on:
  pull_request:
    types: [opened,reopened]

env:
  PR_NUMBER: ${{ github.event.number }}
  BASE_BRANCH: ${{ github.base_ref }}
    
jobs:
  zap_scan_pr:
    runs-on: ubuntu-latest
    name: Scan ZAP website PR
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${BASE_BRANCH}
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://reviews-api-pr-${PR_NUMBER}.herokuapp.com'
          cmd_options: '-a'

  zap_scan_production:
    runs-on: ubuntu-latest
    name: Scan ZAP website Production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://asylum-connect-api.herokuapp.com'
          cmd_options: '-a'