on:
  pull_request:
    types: [opened, reopened]
  # push:
  #   branches:
  #     - main

env:
  PR_NUMBER: ${{ github.event.number }}
  BASE_BRANCH: ${{ github.base_ref }}

jobs:
  zap_scan_staging_baseline:
    runs-on: ubuntu-latest
    name: Scan ZAP website Baseline Staging
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          ref: code-security
      - name: ZAP Scan
        uses: zaproxy/action-baseline@7cea08522cd386f6c675776d5e4296aecf61f33b # v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://inreach-api-v1-git-dev-weareinreach.vercel.app/'
          cmd_options: '-a'

  zap_scan_production_baseline:
    runs-on: ubuntu-latest
    name: Scan ZAP website Baseline Production
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@7cea08522cd386f6c675776d5e4296aecf61f33b # v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://api.inreach.org'
          cmd_options: '-a'

  zap_scan_staging_full:
    runs-on: ubuntu-latest
    name: Scan ZAP website Full Staging
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          ref: code-security
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@6eade0f93b10fad8cfb4e63b979703a2cbd0cc98 # v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://inreach-api-v1-git-dev-weareinreach.vercel.app/'
          cmd_options: '-a'

  zap_scan_production_full:
    runs-on: ubuntu-latest
    name: Scan ZAP website Full Production
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@6eade0f93b10fad8cfb4e63b979703a2cbd0cc98 # v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://api.inreach.org'
          cmd_options: '-a'

  zap_scan_staging_api:
    runs-on: ubuntu-latest
    name: Scan ZAP website API Staging
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          ref: code-security
      - name: ZAP Scan
        uses: zaproxy/action-api-scan@6c29b04d78969bf586f2d4ea15c613d2dfb49d07 # v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://inreach-api-v1-git-dev-weareinreach.vercel.app/'
          cmd_options: '-a'

  zap_scan_production_api:
    runs-on: ubuntu-latest
    name: Scan ZAP website API Production
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-api-scan@6c29b04d78969bf586f2d4ea15c613d2dfb49d07 # v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://api.inreach.org'
          cmd_options: '-a'
